# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'Facebook-iOS-SDK', '~> 3.23'
pod 'RestKit', '~>  0.20.0'
pod 'googleplus-ios-sdk', '~>  1.7' 
pod 'Google-Maps-iOS-SDK', '~> 1.9'
pod 'Parse', '~> 1.7'
pod 'ParseFacebookUtils'

target 'Huellas' do

end

target 'HuellasTests' do

end

